canary_example: canary_example.c
	gcc -std=c99 -no-pie canary_example.c -o canary_example
canary_example_puts: canary_example_puts.c
	gcc -std=c99 -no-pie canary_example_puts.c -o canary_example_puts
canary_example_putchar: canary_example_putchar.c
	gcc -std=c99 -no-pie canary_example_putchar.c -o canary_example_putchar
