name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
     - name: Standard checkout
       uses: actions/checkout@v3
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
     - name: Build and export
       uses: docker/build-push-action@v5
       with:
            context: .
            file: ./Dockerfile
            tags: ashnazg
            outputs: type=oci,dest=/tmp/image.tar
            cache-from: type=gha
            cache-to: type=gha,mode=max
     - name: Test
       run: |
            docker load -i /tmp/image.tar
            docker images
            docker run ashnazg pytest -vvv --durations=0 --color=yes
